version: '2'
services:
  ir-service:
    network_mode: host
    restart: always
    build: ./ir
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
